//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookPrivacyPlugin.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutlookPrivacyPlugin.Language.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect passphrase possibly entered..
        /// </summary>
        public static string ErrorBadPassphrase {
            get {
                return ResourceManager.GetString("ErrorBadPassphrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only sign/encrypt plain text mails. Please change the format, or disable signing/encrypting for this mail..
        /// </summary>
        public static string ErrorInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a recipient when encrypting. No keys were detected/selected..
        /// </summary>
        public static string ErrorInvalidRecipientKey {
            get {
                return ResourceManager.GetString("ErrorInvalidRecipientKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook Privacy Plugin cannot help here, message is not encrypted..
        /// </summary>
        public static string ErrorMsgNotEncrypted {
            get {
                return ResourceManager.GetString("ErrorMsgNotEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook Privacy cannot help here, message is not signed..
        /// </summary>
        public static string ErrorMsgNotSigned {
            get {
                return ResourceManager.GetString("ErrorMsgNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, unable to determine senders address..
        /// </summary>
        public static string ErrorUnableToDetermineSenderAddress {
            get {
                return ResourceManager.GetString("ErrorUnableToDetermineSenderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message decrypted..
        /// </summary>
        public static string MsgDecrypt {
            get {
                return ResourceManager.GetString("MsgDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message decrypted. Valid signature.
        /// </summary>
        public static string MsgDecryptValidSig {
            get {
                return ResourceManager.GetString("MsgDecryptValidSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed integrity check!.
        /// </summary>
        public static string MsgFailedIntegrityCheck {
            get {
                return ResourceManager.GetString("MsgFailedIntegrityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signature from &quot;{0}&quot; with KeyId {1}..
        /// </summary>
        public static string MsgInvalidSig {
            get {
                return ResourceManager.GetString("MsgInvalidSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify signature, missing public key..
        /// </summary>
        public static string MsgSigMissingPubKey {
            get {
                return ResourceManager.GetString("MsgSigMissingPubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was unsigned..
        /// </summary>
        public static string MsgUnsigned {
            get {
                return ResourceManager.GetString("MsgUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid signature from &quot;{0}&quot; with KeyId {1}..
        /// </summary>
        public static string MsgValidSig {
            get {
                return ResourceManager.GetString("MsgValidSig", resourceCulture);
            }
        }
    }
}
